version: 1.0.{build}
configuration: Release
platform: x86
build:
  project: Mouse-Button-Swap.sln
  verbosity: minimal

after_build:
  - cmd: 7z a Mouse-Button-Swap.zip %APPVEYOR_BUILD_FOLDER%\bin\x86\Release\*.exe

artifacts:
  - path: bin\x86\Release\Mouse-Button-Swap.exe
    name: MyApp
    
  - path: Mouse-Button-Swap.zip
    name: MyAppZip
